// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *Withdrawal) SizeSSZ() uint32 {
	return 8 + 8 + 20 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Withdrawal) DefineSSZ(codec ssz.CodecI) {
	ssz.DefineUint64(codec, &obj.Index)        // Field  (0) -     Index -  8 bytes
	ssz.DefineUint64(codec, &obj.Validator)    // Field  (1) - Validator -  8 bytes
	ssz.DefineStaticBytes(codec, &obj.Address) // Field  (2) -   Address - 20 bytes
	ssz.DefineUint64(codec, &obj.Amount)       // Field  (3) -    Amount -  8 bytes
}
