// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SingleFieldTestStruct) SizeSSZ() uint32 {
	return 1
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SingleFieldTestStruct) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint8(codec, &obj.A) // Field  (0) - A - 1 bytes
}
