// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *Transfer) SizeSSZ() uint32 {
	return 8 + 8 + 8 + 8 + 8 + 48 + 96
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Transfer) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.Sender)           // Field  (0) -    Sender -  8 bytes
	ssz.DefineUint64(codec, &obj.Recipient)        // Field  (1) - Recipient -  8 bytes
	ssz.DefineUint64(codec, &obj.Amount)           // Field  (2) -    Amount -  8 bytes
	ssz.DefineUint64(codec, &obj.Fee)              // Field  (3) -       Fee -  8 bytes
	ssz.DefineUint64(codec, &obj.Slot)             // Field  (4) -      Slot -  8 bytes
	ssz.DefineStaticBytes(codec, obj.Pubkey[:])    // Field  (5) -    Pubkey - 48 bytes
	ssz.DefineStaticBytes(codec, obj.Signature[:]) // Field  (6) - Signature - 96 bytes
}
