// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *BeaconBlockHeader) SizeSSZ() uint32 {
	return 8 + 8 + 32 + 32 + 32
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *BeaconBlockHeader) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.Slot)            // Field  (0) -          Slot -  8 bytes
	ssz.DefineUint64(codec, &obj.ProposerIndex)   // Field  (1) - ProposerIndex -  8 bytes
	ssz.DefineStaticBytes(codec, &obj.ParentRoot) // Field  (2) -    ParentRoot - 32 bytes
	ssz.DefineStaticBytes(codec, &obj.StateRoot)  // Field  (3) -     StateRoot - 32 bytes
	ssz.DefineStaticBytes(codec, &obj.BodyRoot)   // Field  (4) -      BodyRoot - 32 bytes
}
