// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// Cached static size computed on package init.
var staticSizeCacheDeposit = 33*32 + new(DepositData).SizeSSZ()

// SizeSSZ returns the total size of the static ssz object.
func (obj *Deposit) SizeSSZ() uint32 {
	return staticSizeCacheDeposit
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Deposit) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineArrayOfStaticBytes(codec, obj.Proof[:]) // Field  (0) - Proof - 1056 bytes
	ssz.DefineStaticObject(codec, &obj.Data)          // Field  (1) -  Data -    ? bytes (DepositData)
}
