// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SyncCommittee) SizeSSZ() uint32 {
	return 512*48 + 48
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SyncCommittee) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUnsafeArrayOfStaticBytes(codec, obj.PubKeys[:]) // Field  (0) -         PubKeys - 24576 bytes
	ssz.DefineStaticBytes(codec, &obj.AggregatePubKey)        // Field  (1) - AggregatePubKey -    48 bytes
}
