// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *Fork) SizeSSZ() uint32 {
	return 4 + 4 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Fork) DefineSSZ(codec ssz.CodecI) {
	ssz.DefineStaticBytes(codec, &obj.PreviousVersion) // Field  (0) - PreviousVersion - 4 bytes
	ssz.DefineStaticBytes(codec, &obj.CurrentVersion)  // Field  (1) -  CurrentVersion - 4 bytes
	ssz.DefineUint64(codec, &obj.Epoch)                // Field  (2) -           Epoch - 8 bytes
}
