// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SmallTestStruct) SizeSSZ() uint32 {
	return 1 + 1
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SmallTestStruct) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineArrayOfBits(codec, &obj.A, 2) // Field  (0) - A - 1 bytes
	ssz.DefineArrayOfBits(codec, &obj.B, 2) // Field  (1) - B - 1 bytes
}
