// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *HistoricalBatch) SizeSSZ() uint32 {
	return 8192*32 + 8192*32
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *HistoricalBatch) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineArrayOfStaticBytes[[8192]Hash, Hash](codec, &obj.BlockRoots) // Field  (0) - BlockRoots - 262144 bytes
	ssz.DefineArrayOfStaticBytes[Roots, Hash](codec, &obj.StateRoots)      // Field  (1) - StateRoots - 262144 bytes
}
