// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *VoluntaryExit) SizeSSZ() uint32 {
	return 8 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *VoluntaryExit) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.Epoch)          // Field  (0) -          Epoch - 8 bytes
	ssz.DefineUint64(codec, &obj.ValidatorIndex) // Field  (1) - ValidatorIndex - 8 bytes
}
