// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SmallTestStructMonolith) SizeSSZ(sizer *ssz.Sizer) (size uint32) {
	if sizer.Fork() >= ssz.ForkUnknown {
		size += 2
	}
	size += 2
	return size
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SmallTestStructMonolith) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint16PointerOnFork(codec, &obj.A, ssz.ForkFilter{Added: ssz.ForkUnknown}) // Field  (0) - A - 2 bytes
	ssz.DefineUint16(codec, &obj.B)                                                      // Field  (1) - B - 2 bytes
}
