// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *Eth1Block) SizeSSZ(sizer *ssz.Sizer) uint32 {
	return 8 + 32 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Eth1Block) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.Timestamp)        // Field  (0) -    Timestamp -  8 bytes
	ssz.DefineStaticBytes(codec, &obj.DepositRoot) // Field  (1) -  DepositRoot - 32 bytes
	ssz.DefineUint64(codec, &obj.DepositCount)     // Field  (2) - DepositCount -  8 bytes
}
