// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *SyncAggregate) SizeSSZ() uint32 {
	return 64 + 96
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *SyncAggregate) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticBytes(codec, &obj.SyncCommiteeBits)      // Field  (0) -      SyncCommiteeBits - 64 bytes
	ssz.DefineStaticBytes(codec, &obj.SyncCommiteeSignature) // Field  (1) - SyncCommiteeSignature - 96 bytes
}
