// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// Cached static size computed on package init.
var staticSizeCacheProposerSlashing = (*SignedBeaconBlockHeader)(nil).SizeSSZ() + (*SignedBeaconBlockHeader)(nil).SizeSSZ()

// SizeSSZ returns the total size of the static ssz object.
func (obj *ProposerSlashing) SizeSSZ() uint32 {
	return staticSizeCacheProposerSlashing
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *ProposerSlashing) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticObject(codec, &obj.Header1) // Field  (0) - Header1 - ? bytes (SignedBeaconBlockHeader)
	ssz.DefineStaticObject(codec, &obj.Header2) // Field  (1) - Header2 - ? bytes (SignedBeaconBlockHeader)
}
