// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// Cached static size computed on package init.
var staticSizeCacheAttestationData = 8 + 8 + 32 + new(Checkpoint).SizeSSZ() + new(Checkpoint).SizeSSZ()

// SizeSSZ returns the total size of the static ssz object.
func (obj *AttestationData) SizeSSZ() uint32 {
	return staticSizeCacheAttestationData
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *AttestationData) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint64(codec, &obj.Slot)                   // Field  (0) -            Slot -  8 bytes
	ssz.DefineUint64(codec, &obj.Index)                  // Field  (1) -           Index -  8 bytes
	ssz.DefineStaticBytes(codec, obj.BeaconBlockHash[:]) // Field  (2) - BeaconBlockHash - 32 bytes
	ssz.DefineStaticObject(codec, &obj.Source)           // Field  (3) -          Source -  ? bytes (Checkpoint)
	ssz.DefineStaticObject(codec, &obj.Target)           // Field  (4) -          Target -  ? bytes (Checkpoint)
}
