// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *Validator) SizeSSZ() uint32 {
	return 48 + 32 + 8 + 1 + 8 + 8 + 8 + 8
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *Validator) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineStaticBytes(codec, obj.Pubkey[:])                // Field  (0) -                     Pubkey - 48 bytes
	ssz.DefineStaticBytes(codec, obj.WithdrawalCredentials[:]) // Field  (1) -      WithdrawalCredentials - 32 bytes
	ssz.DefineUint64(codec, &obj.EffectiveBalance)             // Field  (2) -           EffectiveBalance -  8 bytes
	ssz.DefineBool(codec, &obj.Slashed)                        // Field  (3) -                    Slashed -  1 bytes
	ssz.DefineUint64(codec, &obj.ActivationEligibilityEpoch)   // Field  (4) - ActivationEligibilityEpoch -  8 bytes
	ssz.DefineUint64(codec, &obj.ActivationEpoch)              // Field  (5) -            ActivationEpoch -  8 bytes
	ssz.DefineUint64(codec, &obj.ExitEpoch)                    // Field  (6) -                  ExitEpoch -  8 bytes
	ssz.DefineUint64(codec, &obj.WithdrawableEpoch)            // Field  (7) -          WithdrawableEpoch -  8 bytes
}
