// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *FixedTestStruct) SizeSSZ() uint32 {
	return 1 + 1 + 1
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *FixedTestStruct) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineArrayOfBits(codec, &obj.A, 1) // Field  (0) - A - 1 bytes
	ssz.DefineArrayOfBits(codec, &obj.B, 8) // Field  (1) - B - 1 bytes
	ssz.DefineArrayOfBits(codec, &obj.C, 4) // Field  (2) - C - 1 bytes
}
