// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *HistoricalSummary) SizeSSZ() uint32 {
	return 32 + 32
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *HistoricalSummary) DefineSSZ(codec ssz.CodecI) {
	ssz.DefineStaticBytes(codec, &obj.BlockSummaryRoot) // Field  (0) - BlockSummaryRoot - 32 bytes
	ssz.DefineStaticBytes(codec, &obj.StateSummaryRoot) // Field  (1) - StateSummaryRoot - 32 bytes
}
