// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// Cached static size computed on package init.
var staticSizeCacheBeaconBlockBodyBellatrix = ssz.PrecomputeStaticSizeCache((*BeaconBlockBodyBellatrix)(nil))

// SizeSSZ returns either the static size of the object if fixed == true, or
// the total size otherwise.
func (obj *BeaconBlockBodyBellatrix) SizeSSZ(sizer *ssz.Sizer, fixed bool) (size uint32) {
	// Load static size if already precomputed, calculate otherwise
	if fork := int(sizer.Fork()); fork < len(staticSizeCacheBeaconBlockBodyBellatrix) {
		size = staticSizeCacheBeaconBlockBodyBellatrix[fork]
	} else {
		size = 96 + (*Eth1Data)(nil).SizeSSZ(sizer) + 32 + 4 + 4 + 4 + 4 + 4 + (*SyncAggregate)(nil).SizeSSZ(sizer) + 4
	}
	// Either return the static size or accumulate the dynamic too
	if fixed {
		return size
	}
	size += ssz.SizeSliceOfStaticObjects(sizer, obj.ProposerSlashings)
	size += ssz.SizeSliceOfDynamicObjects(sizer, obj.AttesterSlashings)
	size += ssz.SizeSliceOfDynamicObjects(sizer, obj.Attestations)
	size += ssz.SizeSliceOfStaticObjects(sizer, obj.Deposits)
	size += ssz.SizeSliceOfStaticObjects(sizer, obj.VoluntaryExits)
	size += ssz.SizeDynamicObject(sizer, obj.ExecutionPayload)

	return size
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *BeaconBlockBodyBellatrix) DefineSSZ(codec *ssz.Codec) {
	// Define the static data (fields and dynamic offsets)
	ssz.DefineStaticBytes(codec, &obj.RandaoReveal)                         // Field  (0) -      RandaoReveal - 96 bytes
	ssz.DefineStaticObject(codec, &obj.Eth1Data)                            // Field  (1) -          Eth1Data -  ? bytes (Eth1Data)
	ssz.DefineStaticBytes(codec, &obj.Graffiti)                             // Field  (2) -          Graffiti - 32 bytes
	ssz.DefineSliceOfStaticObjectsOffset(codec, &obj.ProposerSlashings, 16) // Offset (3) - ProposerSlashings -  4 bytes
	ssz.DefineSliceOfDynamicObjectsOffset(codec, &obj.AttesterSlashings, 2) // Offset (4) - AttesterSlashings -  4 bytes
	ssz.DefineSliceOfDynamicObjectsOffset(codec, &obj.Attestations, 128)    // Offset (5) -      Attestations -  4 bytes
	ssz.DefineSliceOfStaticObjectsOffset(codec, &obj.Deposits, 16)          // Offset (6) -          Deposits -  4 bytes
	ssz.DefineSliceOfStaticObjectsOffset(codec, &obj.VoluntaryExits, 16)    // Offset (7) -    VoluntaryExits -  4 bytes
	ssz.DefineStaticObject(codec, &obj.SyncAggregate)                       // Field  (8) -     SyncAggregate -  ? bytes (SyncAggregate)
	ssz.DefineDynamicObjectOffset(codec, &obj.ExecutionPayload)             // Offset (9) -  ExecutionPayload -  4 bytes

	// Define the dynamic data (fields)
	ssz.DefineSliceOfStaticObjectsContent(codec, &obj.ProposerSlashings, 16) // Field  (3) - ProposerSlashings - ? bytes
	ssz.DefineSliceOfDynamicObjectsContent(codec, &obj.AttesterSlashings, 2) // Field  (4) - AttesterSlashings - ? bytes
	ssz.DefineSliceOfDynamicObjectsContent(codec, &obj.Attestations, 128)    // Field  (5) -      Attestations - ? bytes
	ssz.DefineSliceOfStaticObjectsContent(codec, &obj.Deposits, 16)          // Field  (6) -          Deposits - ? bytes
	ssz.DefineSliceOfStaticObjectsContent(codec, &obj.VoluntaryExits, 16)    // Field  (7) -    VoluntaryExits - ? bytes
	ssz.DefineDynamicObjectContent(codec, &obj.ExecutionPayload)             // Field  (9) -  ExecutionPayload - ? bytes
}
