// Code generated by github.com/karalabe/ssz. DO NOT EDIT.

package consensus_spec_tests

import "github.com/karalabe/ssz"

// SizeSSZ returns the total size of the static ssz object.
func (obj *FixedTestStruct) SizeSSZ() uint32 {
	return 1 + 8 + 4
}

// DefineSSZ defines how an object is encoded/decoded.
func (obj *FixedTestStruct) DefineSSZ(codec *ssz.Codec) {
	ssz.DefineUint8(codec, &obj.A)  // Field  (0) - A - 1 bytes
	ssz.DefineUint64(codec, &obj.B) // Field  (1) - B - 8 bytes
	ssz.DefineUint32(codec, &obj.C) // Field  (2) - C - 4 bytes
}
